# System-wide configuration defaults
# User-modifiable variables have been moved to group_vars/local.yml
admin_password: 3HeaddedMonkey # Please change right away!
# ansible_folder: '/opt/CrimsonCFG'  # Removed, now user-specific as working_directory
chromium_profile1_name: downloads
cursor_appimage_dir: '{{ user_home }}/AppImage/Cursor'
cursor_appimage_filename: Cursor.AppImage
cursor_appimage_url: https://downloads.cursor.com/production/faa03b17cce93e8a80b7d62d57f5eda6bb6ab9fa/linux/x64/Cursor-1.2.2-x86_64.AppImage
debug: 1
desktop_dotfile_folder: '{{ user_home }}/.local/share/applications'
# git_email: "{{ lookup('env', 'GIT_EMAIL', default=git_email_local | default('user@example.com')) }}"
# git_username: "{{ lookup('env', 'GIT_USERNAME', default=git_username_local | default(user)) }}"
inventory_file: '{{ working_directory }}/hosts.ini'
log_directory: '{{ working_directory }}/log'
oh_my_zsh_install_url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
orca_appimage_dir: '{{ user_home }}/AppImage/OrcaSlicer'
orca_appimage_filename: OrcaSlicer.AppImage
orca_appimage_url: https://github.com/SoftFever/OrcaSlicer/releases/download/v2.3.0/OrcaSlicer_Linux_AppImage_Ubuntu2404_V2.3.0.AppImage
orca_desktop_file: /usr/share/applications/orca-slicer.desktop
powerlevel10k_repo: https://github.com/romkatv/powerlevel10k.git
prism_appimage_dir: '{{ user_home }}/AppImage/PrismLauncher'
prism_appimage_filename: PrismLauncher.AppImage
# user: "{{ lookup('env', 'CRIMSON_USER', default='user') }}"
user_group: '{{ user }}'
user_home: /home/{{ user }}
user_shell: /bin/bash
zsh_plugins:
- name: zsh-autosuggestions
  repo: https://github.com/zsh-users/zsh-autosuggestions.git
- name: zsh-syntax-highlighting
  repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
- name: zsh-completions
  repo: https://github.com/zsh-users/zsh-completions.git
