# CrimsonCFG-Name: Basic Applications
# CrimsonCFG-Description: Install basic system applications and utilities specified in all.yml variables.
# CrimsonCFG-Essential: true
# CrimsonCFG-Essential-Order: 3
---
- name: Install basic applications
  hosts: all
  become: true

  tasks:

    #######################
    # Install basic apt pkgs
    #######################

    - name: Install common APT packages
      ansible.builtin.apt:
        name: "{{ apt_packages }}"
        state: present

    #######################
    # Install basic snap pkgs
    #######################

    - name: Install Snap packages
      community.general.snap:
        name: "{{ item }}"
        state: present
      loop: "{{ snap_packages }}"
