# CrimsonCFG-Name: Timeshift
# CrimsonCFG-Description: Setup Timeshift system backup
# CrimsonCFG-Essential: true
# CrimsonCFG-Essential-Order: 2

---
- name: Install Timeshift and make first backup to root partition
  hosts: all
  become: true

  tasks:

    - name: Ensure Timeshift is installed
      ansible.builtin.package:
        name: timeshift
        state: present

    - name: Get root partition device
      ansible.builtin.command: findmnt -n -o SOURCE /
      register: root_partition
      changed_when: false

    - name: Get root filesystem type
      ansible.builtin.command: findmnt -n -o FSTYPE /
      register: root_fstype
      changed_when: false

    - name: Get UUID of root partition (block device)
      ansible.builtin.command: blkid -s UUID -o value {{ root_partition.stdout }}
      register: root_partition_uuid
      changed_when: false
      when: root_fstype.stdout != "zfs"

    - name: Get ZFS dataset name for root
      ansible.builtin.shell: zfs list -H -o name,mountpoint | awk '$2=="/"{print $1}'
      register: zfs_root_dataset
      changed_when: false
      when: root_fstype.stdout == "zfs"

    - name: Get ZFS dataset GUID
      ansible.builtin.command: zfs get -H -o value guid {{ zfs_root_dataset.stdout }}
      register: root_partition_uuid
      changed_when: false
      when: root_fstype.stdout == "zfs"

    - name: Debug root partition UUID or GUID
      ansible.builtin.debug:
        var: root_partition_uuid.stdout

    - name: Fail if root partition UUID could not be determined
      ansible.builtin.fail:
        msg: "Could not determine root partition UUID or GUID. Timeshift may not work as expected."
      when: root_partition_uuid is not defined or not root_partition_uuid.stdout

    - name: Ensure Timeshift is configured to use main disk
      ansible.builtin.copy:
        dest: /etc/timeshift/timeshift.json
        mode: '0600'
        content: |
          {
              "backup_device_uuid" : "{{ root_partition_uuid.stdout }}",
              "parent_device_uuid" : "{{ root_partition_uuid.stdout }}",
              "do_first_run" : "false",
              "btrfs_mode" : "false",
              "include_btrfs_home" : "false",
              "stop_cron_emails" : "false",
              "schedule_monthly" : "false",
              "schedule_weekly" : "false",
              "schedule_daily" : "false",
              "schedule_hourly" : "false",
              "schedule_boot" : "false",
              "count_monthly" : "2",
              "count_weekly" : "3",
              "count_daily" : "2",
              "count_hourly" : "5",
              "count_boot" : "5"
          }

    - name: Create initial snapshot
      ansible.builtin.command: timeshift --create --comments "Pre-install snapshot before installation" --tags D
      changed_when: true

    - name: Enable Timeshift schedules
      ansible.builtin.copy:
        dest: /etc/timeshift/timeshift.json
        mode: '0600'
        content: |
          {
              "backup_device_uuid" : "{{ root_partition_uuid.stdout }}",
              "parent_device_uuid" : "{{ root_partition_uuid.stdout }}",
              "do_first_run" : "false",
              "btrfs_mode" : "false",
              "include_btrfs_home" : "false",
              "stop_cron_emails" : "false",
              "schedule_monthly" : "true",
              "schedule_weekly" : "true",
              "schedule_daily" : "true",
              "schedule_hourly" : "false",
              "schedule_boot" : "false",
              "count_monthly" : "2",
              "count_weekly" : "3",
              "count_daily" : "2",
              "count_hourly" : "5",
              "count_boot" : "5"
          }
