# CrimsonCFG-Name: Timeshift
# CrimsonCFG-Description: Setup Timeshift system backup
# CrimsonCFG-Essential: true
# CrimsonCFG-Essential-Order: 2

---
- name: Install Timeshift and make first backup to root partition
  hosts: all
  become: true

  tasks:

    - name: Get root partition device
      ansible.builtin.command: findmnt -n -o SOURCE /
      register: root_partition
      changed_when: false

    - name: Get root filesystem type
      ansible.builtin.command: findmnt -n -o FSTYPE /
      register: root_fstype
      changed_when: false

    - name: Fail if root filesystem is ZFS (Timeshift not supported)
      ansible.builtin.fail:
        msg: "Timeshift does not support ZFS. Skipping Timeshift setup."
      when: root_fstype.stdout == "zfs"
    
    - name: Ensure Timeshift is installed
      ansible.builtin.package:
        name: timeshift
        state: present

    - name: Get UUID of root partition (block device)
      ansible.builtin.command: blkid -s UUID -o value {{ root_partition.stdout }}
      register: root_partition_uuid
      changed_when: false
      when: root_fstype.stdout != "zfs"

    - name: Debug root partition UUID
      ansible.builtin.debug:
        var: root_partition_uuid.stdout
      when: root_fstype.stdout != "zfs"

    - name: Fail if root partition UUID could not be determined
      ansible.builtin.fail:
        msg: "Could not determine root partition UUID. Timeshift may not work as expected."
      when: (root_fstype.stdout != "zfs") and (root_partition_uuid is not defined or not root_partition_uuid.stdout)

    - name: Ensure Timeshift is configured to use main disk
      ansible.builtin.copy:
        dest: /etc/timeshift/timeshift.json
        mode: '0600'
        content: |
          {
              "backup_device_uuid" : "{{ root_partition_uuid.stdout | trim }}",
              "parent_device_uuid" : "{{ root_partition_uuid.stdout | trim }}",
              "do_first_run" : "false",
              "btrfs_mode" : "false",
              "include_btrfs_home" : "false",
              "stop_cron_emails" : "false",
              "schedule_monthly" : "false",
              "schedule_weekly" : "false",
              "schedule_daily" : "false",
              "schedule_hourly" : "false",
              "schedule_boot" : "false",
              "count_monthly" : "2",
              "count_weekly" : "3",
              "count_daily" : "2",
              "count_hourly" : "5",
              "count_boot" : "5"
          }
      when: root_fstype.stdout != "zfs"

    - name: Validate timeshift.json
      ansible.builtin.command: jq empty /etc/timeshift/timeshift.json
      register: json_check
      failed_when: json_check.rc != 0
      changed_when: false
      when: root_fstype.stdout != "zfs"

    - name: List existing Timeshift snapshots
      ansible.builtin.command: timeshift --list --scripted
      register: timeshift_snapshots
      changed_when: false
      failed_when: false
      when: root_fstype.stdout != "zfs"

    - name: Check if 'Init CrimsonCFG' snapshot exists
      ansible.builtin.set_fact:
        init_crimsoncfg_snapshot_exists: "{{ 'Init CrimsonCFG' in timeshift_snapshots.stdout }}"
      when: root_fstype.stdout != "zfs"

    - name: Create initial snapshot
      ansible.builtin.command: "timeshift --create --scripted --verbose --comments \"Init CrimsonCFG\" --tags D"
      changed_when: true
      when:
        - root_fstype.stdout != "zfs"
        - not init_crimsoncfg_snapshot_exists

    - name: Enable Timeshift schedules
      ansible.builtin.copy:
        dest: /etc/timeshift/timeshift.json
        mode: '0600'
        content: |
          {
              "backup_device_uuid" : "{{ root_partition_uuid.stdout }}",
              "parent_device_uuid" : "{{ root_partition_uuid.stdout }}",
              "do_first_run" : "false",
              "btrfs_mode" : "false",
              "include_btrfs_home" : "false",
              "stop_cron_emails" : "false",
              "schedule_monthly" : "true",
              "schedule_weekly" : "true",
              "schedule_daily" : "true",
              "schedule_hourly" : "false",
              "schedule_boot" : "false",
              "count_monthly" : "2",
              "count_weekly" : "3",
              "count_daily" : "2",
              "count_hourly" : "5",
              "count_boot" : "5"
          }
      when: root_fstype.stdout != "zfs"

    - name: Validate timeshift.json
      ansible.builtin.command: jq empty /etc/timeshift/timeshift.json
      register: json_check
      failed_when: json_check.rc != 0
      changed_when: false
      when: root_fstype.stdout != "zfs"
