# CrimsonCFG-Name: Set GNOME Theme
# CrimsonCFG-Description: Set GNOME Theme
# CrimsonCFG-Essential: false
# CrimsonCFG-RequiredVars: true
---
- name: Set GNOME Theme
  hosts: all
  become: true
  vars_files:
    - "{{ lookup('env', 'HOME') + '/.config/com.crimson.cfg/local.yml' }}"

  pre_tasks:

    - name: Fail if theme_mode is not set
      ansible.builtin.fail:
        msg: "theme_mode variable is not set in local.yml. Please set it to 'light' or 'dark'."
      when: theme_mode is not defined or theme_mode|length == 0

    - name: Fail if user is not set
      ansible.builtin.fail:
        msg: "user variable is not set in local.yml."
      when: user is not defined or user|length == 0

    - name: Validate theme_mode value
      ansible.builtin.fail:
        msg: "theme_mode must be set to 'light' or 'dark' in local.yml. Current value: {{ theme_mode }}"
      when: theme_mode not in ['light', 'dark']

  tasks:

      #######################
      # Get Session/Display
      #######################

    - name: Find active session ID for user
      ansible.builtin.shell: |
        set -o pipefail
        loginctl list-sessions --no-legend | grep '{{ user }}' | awk '{print $1}'
      register: user_session
      changed_when: false

    - name: Get XDG_RUNTIME_DIR for user
      ansible.builtin.shell: |
        echo /run/user/$(id -u {{ user }})
      register: runtime_dir
      changed_when: false

    - name: Debug session info
      ansible.builtin.debug:
        msg: |
          Session ID: {{ user_session.stdout }}
          XDG_RUNTIME_DIR: {{ runtime_dir.stdout }}
          Theme Mode: {{ theme_mode }}

    - name: Debug theme_mode variable
      ansible.builtin.debug:
        msg: |
          theme_mode value: "{{ theme_mode }}"
          theme_mode type: "{{ theme_mode | type_debug }}"
          theme_mode length: "{{ theme_mode | length }}"

      #######################
      # Set Theme Based on theme_mode
      #######################

    - name: Debug color scheme command
      ansible.builtin.debug:
        msg: "Setting color-scheme to: {{ 'prefer-dark' if theme_mode == 'dark' else 'default' }}"

    - name: Set GNOME color scheme based on theme_mode
      ansible.builtin.shell: |
        sudo -u {{ user }} \
          XDG_RUNTIME_DIR={{ runtime_dir.stdout }} \
          DBUS_SESSION_BUS_ADDRESS=unix:path={{ runtime_dir.stdout }}/bus \
          gsettings set org.gnome.desktop.interface color-scheme '{{ "prefer-dark" if theme_mode == "dark" else "default" }}'
      args:
        executable: /bin/bash
    - name: Debug GTK theme command
      ansible.builtin.debug:
        msg: "Setting gtk-theme to: {{ 'Adwaita-dark' if theme_mode == 'dark' else 'Adwaita' }}"

    - name: Set GNOME GTK theme based on theme_mode
      ansible.builtin.shell: |
        sudo -u {{ user }} \
          XDG_RUNTIME_DIR={{ runtime_dir.stdout }} \
          DBUS_SESSION_BUS_ADDRESS=unix:path={{ runtime_dir.stdout }}/bus \
          gsettings set org.gnome.desktop.interface gtk-theme '{{ "Adwaita-dark" if theme_mode == "dark" else "Adwaita" }}'
      args:
        executable: /bin/bash

