# CrimsonCFG-Name: Basic Applications
# CrimsonCFG-Description: Install basic system applications and utilities specified in local.yml variables.
# CrimsonCFG-Essential: true
# CrimsonCFG-Essential-Order: 3
---
- name: Install basic applications
  hosts: localhost
  become: true
  vars_files:
    - "{{ lookup('env', 'HOME') + '/.config/com.crimson.cfg/local.yml' }}"
  tasks:

    #######################
    # Install basic apt pkgs
    #######################

    - name: Check if APT package is installed
      ansible.builtin.shell: "dpkg -s {{ item }} | grep -q '^Status: install'"
      register: apt_installed
      ignore_errors: true
      changed_when: false
      loop: "{{ apt_packages }}"

    - name: Combine package names and install results
      ansible.builtin.set_fact:
        apt_pkg_status: "{{ apt_packages | zip(apt_installed.results) | list }}"

    - name: Install common APT packages
      ansible.builtin.apt:
        name: "{{ item.0 }}"
        state: present
      when: item.1.rc != 0
      loop: "{{ apt_pkg_status }}"